Criando validação para valores negativos
codenation-dev/squad-2-ad-python-2 pull request #3
Opened 2019-07-10 00:35 UTC by YouFool

PR criado para realizar ajustes referentes a issue #1 

Ainda é necessário realizar a validação referente à % máxima ser menor que a % mínima

2019-07-10 02:22 UTC, YouFool commented
Realizada validação para discriminar %min > %max

2019-07-10 16:50 UTC, jmiguelh commented
@YouFool ,
O código está quebrado pois a chamada da validação está: ```validate_percent_max_maior_que_percent_min``` e a definição dela está como: 
```validate_percent_max_menor_que_percent_min```

2019-07-10 16:53 UTC, jmiguelh requested changes
O código está quebrado pois a chamada da validação está: ```validate_percent_max_maior_que_percent_min``` e a definição dela está como:
```validate_percent_max_menor_que_percent_min```  
O Restante está 100%!

2019-07-10 23:32 UTC, YouFool commented
Realmente, ao alterar o nome da function no último momento acabei quebrando a validação. Agora está validando corretamente 😸

2019-07-11 17:56 UTC, jmiguelh approved these changes

2019-07-13 12:25 UTC, merged